# Generated by Django 2.2.3 on 2019-07-31 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('license', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('chief_vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vets.Vet')),
            ],
        ),
    ]
